import re

ENDING_PUNCTUATIONS = ['.', '!']
SPACE_REMOVER_PATTERN = re.compile(r'\s+')
ENGINE = 'text-davinci-003'
TEMPERATURE = 0.7
MAX_TOKENS = 80
TOP_P = 1.
FREQUENCY_PENALTY = 1.
PRESENCE_PENALTY = 1.
N = 1
